CREATE TABLE MOVIES (
    ID   		INTEGER NOT NULL AUTO_INCREMENT,
    YEAR 		INTEGER NOT NULL,
    TITLE 		VARCHAR(128) NOT NULL,
    STUDIOS 	VARCHAR(128) NOT NULL,
    PRODUCERS 	VARCHAR(128) NOT NULL,
    WINNER 		BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);